codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: 95%
        paths:
          - "!crates/novomodelo-solver/"
      solver:
        target: 90%
        paths:
          - "crates/novomodelo-solver/"
